### ISSUE TITLE
If you try to run the project, you get a build error

### ISSUE THREAD

**Issue by Wolfr** [Dietr/hashi-boilerplate#1]
I got this error when trying to run the project with `jekyll serve`:

```
Generating... 
  Conversion error: Jekyll::Converters::Scss encountered an error while converting '/css/main.scss':
                    File to import not found or unreadable: ../_vendor/chopstick-tools/tools.functions. Load path: /Users/johanronsse/Sites/hashi-boilerplate/_scss on line 8
```

I suspect this is because `_vendor` is in `.gitignore` yet I need the files to run the initial CSS.

**Comment by Dietr** [comment]
Did you run the install script or the following `bundle install && bower install`?

**Comment by Wolfr** [comment]
Got it working. Not sure if it there was really a problem – probably just me messing up with the commands – so you can close this one 👍 I put in a PR to clarify what to do.

**Comment by Dietr** [comment]
Could be that the install script is not really that good. It may be better to just do it manually.

**Comment by Wolfr** [comment]
Maybe just put the instructions in the repo, the script does so little it's probably better to expose what it actually does.
